name: PR Validation

on: [ pull_request ]

jobs:
  static-analysis:
    name: Static analysis
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [ 20.x ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run type check
        run: npm run typecheck
      - name: Run ESLint
        run: npm run lint
      - name: Build
        run: npm run build
  
  unit:
    name: Unit tests
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [ 20.x ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use latest stable Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Unit tests
        run: npm run test:unit:ci

  e2e:
    name: End-to-end tests
    timeout-minutes: 60
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
